name = "ReplicationProject"
uuid = "37c02198-9961-436a-836d-5845010e8c6b"
authors = ["Karina P. <karina.pavlovich@sciencespo.fr> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
